apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: songs-service
                port:
                  number: 8081
            path: /api/v1/songs(/|$)(.*)
    - http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: resources-service
                port:
                  number: 8080
            path: /api/v1/resources(/|$)(.*)