apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: resources-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
