apiVersion: v1
kind: Service
metadata:
  name: resources-pg-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    apps.kubernetes.io/pod-index: "0"
    app: postgresql-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
