apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
  labels:
    app: songs-service
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/songs-pv"
  claimRef:
    name: songs-pvc
    namespace: {{ .Values.namespace }}


