apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: songs-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30031
