apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service-deployment
  labels:
    app: resources-service
  namespace: k8s-program
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: resources-service
  template:
    metadata:
      labels:
        app: resources-service
    spec:
      containers:
        - name: resources-service
          image: localhost:5000/resources-image:2.0
          ports:
            - name: app-port
              containerPort: 8080
          env:
            - name: SONGS_MS_URL
              valueFrom:
                configMapKeyRef:
                  name: services-cm
                  key: songsMsUrl
            - name: RESOURCES_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: services-cm
                  key: resourcesDbUrl
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: app-port
            failureThreshold: 1
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: app-port
            failureThreshold: 180
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/beans
              port: app-port
            initialDelaySeconds: 5
            periodSeconds: 5
